AllCops:
  NewCops: disable
  TargetRubyVersion: 2.7.4

Style/SymbolArray:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
Style/WordArray:
  EnforcedStyle: brackets

Layout/SpaceAroundMethodCallOperator:
 Enabled: False
Layout/SpaceInLambdaLiteral:
  Enabled: true
  EnforcedStyle: require_space
# Commonly used screens these days easily fit more than 80 characters.
Layout/LineLength:
  Max: 120


Metrics/AbcSize:
  Enabled: false
# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength:
  Enabled: true
  Max: 20

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'it']

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
